### ISSUE TITLE
4.23 MacOS Monterey 12.2.1 not working?

### ISSUE THREAD

**Issue by nieric** [thisiscam/math-with-slack#40]
Hello,

I seemingly cannot get this to work on MacOS Monterey 12.2.1 with Slack 4.23. 
I've reinstalled Slack multiple times, and went through the computer to find files (eg. in Library/) left over from old installations that did not get removed. Still, seemingly unsuccessful.

PS.
Additionally, using the --codesign flag seems to work, but when running the scripts manually in their folder, I get
```
% sudo sh macos-codesign-mws.sh  
Executable=/Applications/Slack.app/Contents/MacOS/Slack
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/slack-entitlements.lKA6pFuP: unrecognized blob type (accepting blindly)
/var/folders/zz/zyxvpxvq6csfxvn_n0000000000000/T/slack-entitlements.lKA6pFuP: invalid length in entitlement blob
```

This probably has nothing to do with the other issue, just adding it as a note. DS.

**Comment by albinahlback** [comment]
What Python version do you use? Have you tried using Python 3.6? That is what is currently tested for this project (however, that is on macOS 11.6 machines).

**Comment by thisiscam** [comment]
I don't believe Python version matters here AFAIK

**Comment by thisiscam** [comment]
> Additionally, using the --codesign flag seems to work, but when running the scripts manually in their folder, I get

If the `codesign` works then it's probably fine. There were some update to MacOS that I had fixed in the main script, but forgot to update the the separate bash scripts.

**Comment by nieric** [comment]
Hi @thisiscam,
great, but I still cannot seem to get Latex to render in Slack on my machine. I've had no issues with this on Windows before.

Since there is no apparent error when running the script, does anyone have a suggestion what I could do to figure out what is wrong?

**Comment by thisiscam** [comment]
Perhaps you can try `SLACK_DEVELOPER_MENU=1 open /Applications/Slack.app` (change to your Slack.app path). Doing this should open slack. You can then right click anywhere in the UI and get an "inspect element" option. This gives you the chromium debugger. Look for log messages and console outputs, see if there are any related errors?

**Comment by thisiscam** [comment]
Before doing that, make sure you got a fresh install of slack and the plugin first

**Comment by JoeyAndBlueWhale** [comment]
I did this and found 1 issue and 3 warnings. The issue is
`A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. Starting in Chrome 101, the amount of information available in the User Agent string will be reduced.
To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData.
Note that for performance reasons, only the first access to one of the properties is shown.
`
Three warnings are
<img width="554" alt="Screen Shot 2022-06-08 at 01 02 40" src="https://user-images.githubusercontent.com/24945663/172543194-8d0f4602-d90c-45d1-9be6-fde6d3adf471.png">

**Comment by thisiscam** [comment]
My script is working. I have the same "issue" but I don't see those warnings. So at least we can disregard that issue. 

Before getting into anything deeper, what's your result of:
```bash
ls /Applications/Slack.app/Contents/Resources/app-*
```
, after installing the script?

**Comment by JoeyAndBlueWhale** [comment]
> My script is working. I have the same "issue" but I don't see those warnings. So at least we can disregard that issue.
> 
> Before getting into anything deeper, what's your result of:
> 
> ```shell
> ls /Applications/Slack.app/Contents/Resources/app-*
> ```
> 
> , after installing the script?

`ents/Resources/app-*
/Applications/Slack.app/Contents/Resources/app-arm64.asar
/Applications/Slack.app/Contents/Resources/app-x64.asar
/Applications/Slack.app/Contents/Resources/app-x64.asar.mwsbak
/Applications/Slack.app/Contents/Resources/app-arm64.asar.unpacked:
dist		node_modules
/Applications/Slack.app/Contents/Resources/app-x64.asar.unpacked:
dist		node_modules
`

**Comment by thisiscam** [comment]
Aha, the script did not properly recognize your M1 chip. Let me take a look in an hour

**Comment by thisiscam** [comment]
@JoeyAndBlueWhale 

What command did you use to install the script? 
And what's your output of `python -c 'import platform; print(platform.machine())'`?

**Comment by thisiscam** [comment]
I think I found the issue. It's likely that people who run into this issue are using M1 chip apple with Rosette-ed python interpreter. I don't have an M1 chip, but I implemented [this answer](https://stackoverflow.com/a/69853058) in #45 --- hopefully this will solve the problem!

**Comment by JoeyAndBlueWhale** [comment]
> python -c 'import platform; print(platform.machine())'

`x86_64`

**Comment by JoeyAndBlueWhale** [comment]
> What command did you use to install the script?

`sudo python3 math-with-slack.py --macos-codesign
`

**Comment by JoeyAndBlueWhale** [comment]
> I think I found the issue. It's likely that people who run into this issue are using M1 chip apple with Rosette-ed python interpreter. I don't have an M1 chip, but I implemented [this answer](https://stackoverflow.com/a/69853058) in #45 --- hopefully this will solve the problem!

I just downloaded the latest version of your code and reinstalled it, it still doesn't work.

**Comment by JoeyAndBlueWhale** [comment]
> I think I found the issue. It's likely that people who run into this issue are using M1 chip apple with Rosette-ed python interpreter. I don't have an M1 chip, but I implemented [this answer](https://stackoverflow.com/a/69853058) in #45 --- hopefully this will solve the problem!

It worked! Thank you!
